# Shared Data Configuration for Pokemon Classifier

# Dataset paths
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  splits_dir: "data/splits"
  
  # Original datasets
  gen1_3_dataset: "data/raw/gen1_3_pokemon"  # Your 900MB dataset
  
  # Processed data
  images_dir: "data/processed/images"
  metadata_dir: "data/processed/metadata"
  yolo_dataset: "data/processed/yolo_dataset"
  clip_dataset: "data/processed/clip_dataset"
  smolvm_dataset: "data/processed/smolvm_dataset"

# Data processing
processing:
  image_size: 416  # Standard size for YOLO, can be resized for other models
  batch_size: 16
  num_workers: 4
  
  # Shared augmentation settings
  augmentation:
    rotation: 15
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1

# Dataset splits
splits:
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  
# Pokemon generations
generations:
  baseline: [1, 2, 3]  # 386 Pokemon
  full: [1, 2, 3, 4, 5, 6, 7, 8, 9]  # 1025 Pokemon

# Hugging Face settings
huggingface:
  yolo_dataset_name: "your-username/pokemon-yolo-gen1-3"
  clip_dataset_name: "your-username/pokemon-clip-gen1-3"
  smolvm_dataset_name: "your-username/pokemon-smolvm-gen1-3" 