# Shared Data Configuration for Pokemon Classifier

# Dataset paths
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  splits_dir: "data/splits"
  
  # Original datasets
  all_pokemon_dataset: "data/raw/all_pokemon"  # All 1025 Pokemon dataset
  
  # Processed data
  images_dir: "data/processed/images"
  metadata_dir: "data/processed/metadata"
  yolo_dataset: "data/processed/yolo_dataset"
  clip_dataset: "data/processed/clip_dataset"
  smolvm_dataset: "data/processed/smolvm_dataset"

# Data processing
processing:
  image_size: 416  # Standard size for YOLO, can be resized for other models
  batch_size: 16
  num_workers: 4
  
  # Shared augmentation settings
  augmentation:
    rotation: 15
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1

# Dataset splits
splits:
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  
# Pokemon generations
generations:
  original_blog: [1, 2, 3, 4, 5, 6, 7, 8, 9]  # 1025 Pokemon (original blog used all)
  full: [1, 2, 3, 4, 5, 6, 7, 8, 9]  # 1025 Pokemon (current focus)

# Hugging Face settings
huggingface:
  yolo_dataset_name: "liuhuanjim013/pokemon-yolo-1025"
  clip_dataset_name: "liuhuanjim013/pokemon-clip-1025"
  smolvm_dataset_name: "liuhuanjim013/pokemon-smolvm-1025" 